services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: dental_clinic
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:


